meta_product_name: "Violaine Quinchon"
meta_title: "Violaine Quinchon"
meta_description: "Violaine Quinchon, Responsable Communication Interne"
meta_image: "me.svg" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
